### ISSUE TITLE
Incorrect icons in 2015-12-28 OSM build

### ISSUE THREAD

**Issue by seanlynch** [ge0rg/aprsdroid#120]
In particular, /$ now shows up as an ambulance instead of a phone, but all the icons look inappropriate.

**Comment by ge0rg** [comment]
Whoops, sorry. I've been playing around with the [new APRS symbols by Hessu](http://blog.aprs.fi/2015/11/new-symbol-graphics-and-better-support.html) and messed them up. I'll create a proper build in the next days.

**Comment by seanlynch** [comment]
Any ETA on this?

**Comment by ge0rg** [comment]
Sorry, I've been pretty busy with other things. [Here is a fixed APK](http://aprsdroid.org/download/builds/APRSdroid-gl-2016-02-23_osm.apk), please test and report if it is alright for you.

**Comment by seanlynch** [comment]
It works. Thanks! I prefer the old icons, though. Sorry to take so long to
test.

**Comment by Hibby** [comment]
I've always been curious about using the [OSM symbols](http://wiki.openstreetmap.org/wiki/Standard_tile_layer) as APRS icons - maybe, given the OSM APK is using the OSM Mapnik rendering, these would fit in better. 

As goes the old saying, _how hard can it be?_

**Comment by seanlynch** [comment]
I do like the look of the OSM symbols, though they appear to be a fixed 16x16 pixels, which won't be very visible on small-dot-pitch screens. Hessu's symbols are scalable, I just don't really like their aesthetic, because they are more detailed and thus add visual clutter. I think a straight across translation of the old symbols (or some of the OSM symbols) would be ideal. Maybe the unicode transport and map symbols from Symbola? Those are monochrome, though:

🚨👮📞✈♿✚🏠🔥⛺🏍💻⛵🚆🏥📪

**Comment by Hibby** [comment]
The OSM Symbols should all be scalable vector graphics, see [https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols](their github), and not tied to any set size. There's a few [other options](https://github.com/gmgeo/osmic) too, one of which I actually really liked but can't find again, I'll have to have a hunt around for it.

Unicode support could be great, but that relies on vendors supplying the complete symbolset, which we can't rely on (I can't see the 10th symbol in sequence above) and the implementation differs from place to place.

I guess another issue is by diverging to OSM or otherwise we're looking at making a whole new symbol set that deviates from what has become the de-facto standard... It's a lot of time and effort to sink in to making a lot of OMs confused and grumpy, however I do agree with your point on Hessu's updated symbol pack. 
I've never been a big fan of the original symbols either, and I'm sure buried away somewhere in my home git repos there's a replacement set I started work on based on an OSM symbol pack. I'll look it up later and see if it's any good.

**Comment by seanlynch** [comment]
I didn't mean unicode itself, just the glyphs from Symbola, though they're obviously not complete. But then again neither are the OSM symbols, and the ones that aren't in Symbola or OSM are probably pretty easy to make, or they could be taken from Hessu.

**Comment by seanlynch** [comment]
While the text of the link to the symbols is correct, the actual href is not. I had to copy and paste the text to go there. Those look like they're still in the process of being replaced with scalable icons, though I see a lot of SVG ones there.

**Comment by ge0rg** [comment]
Indeed, replacing the symbols with some other set is a task too hard.

@seanlynch Hes has his own github repo for the symbols, you might or might not convince him to simple them down...
