### ISSUE TITLE
Feature Request: Export Log to file

### ISSUE THREAD

**Issue by mflane** [ge0rg/aprsdroid#129]
I would like to be able to export the log to a file on my device in order to use, search, and manipulate later.

**Comment by ge0rg** [comment]
I can not promise anything any time soon, but which kind of log file format are you anticipating?

KML? APRS-IS style? Something else?

**Comment by laemmy** [comment]
I've received some packets with telemetry data from PSAT-1 an hour ago with this great application. That was the first time I've missed an export function. It would be nice if a log could be exported from a specific station. Also the full log export would be great. APRS-IS style should be fine in my point of view.

**Comment by mflane** [comment]
My apologies, I some how missed Georg's reply...

I agree, APRS-IS format would be great. And I would love to see a larger
buffer for the log, or perhaps even an adjustable buffer size for the log.

**Comment by ge0rg** [comment]
IIRC, APRS-IS format is lacking timestamp information. I could probably insert APRS timestamps into the packets, but that could cause side effects. It's also possible to just prefix each line with the timestamp when it was received, but then you'd need to preprocess them before feeding them into another APRS app...

**Comment by laemmy** [comment]
Prefix each line with timestmap would be fine in my opinion. Preprocess for other applications could be easily done by a perl script for example.

**Comment by ge0rg** [comment]
It looks like [somebody was wrong on the internet](https://twitter.com/DM9KS/status/866635480615587840) and because I don't like such things, I've finally implemented log export: https://aprsdroid.org/download/builds/APRSdroid-gl-2017-05-23.apk

You can export from any of the main views (full log for the last two days), or from a station view (log filtered on sender callsign; will probably not work for objects), it will create a file `aprsdroid-yyyyMMdd-hhmm.log` on the SD card / storage, and automatically pop up a list of apps that take files (e.g. e-mail).

The file format is as follows:

* `yyyy-MM-dd hh:mm:ss` (local time)
* tab stop
* `RX` or `TX` for the direction
* tab stop
* APRS packet in TNC2 format
* new line


Please test and report back.
