### ISSUE TITLE
ArrayIndexOutOfBoundsException in AFSK mode, callsign too long

### ISSUE THREAD

**Issue by pyrog** [ge0rg/aprsdroid#163]
Try AFSK mode. I press the _"Single Shot button"_, hear nothing.

This message is displayed in the log:
`java.lang.ArrayIndexOutOfBoundsException: length=7; index=7`

Tested on android 6.0.1

**Comment by ge0rg** [comment]
Does that happen more often? Unfortunately, such errors are trapped in APRSdroid and not displayed on screen. I'd love to get a stack trace, but that needs ADB debugging. Maybe you can provide such a log? On rooted devices, CatLog should be sufficient (https://github.com/ge0rg/aprsdroid/wiki/Reporting-Bugs), otherwise, a USB connection is probably needed.

**Comment by nicholashamblin** [comment]
i am having the same error mesage.. its frustrating but i like a mystery.
java.lang.ArrayIndexOutOfBoundsException: length=7; index=7

im using motorola turbo 2
aprs cable from amazon (works fine for rx/tx with other apps.)
baofeng uv-5r handheld radio.

please help.

**Comment by nicholashamblin** [comment]
i was having the same issue. however it fixed itself.. yeaaaa.

**Comment by dano1o** [comment]
Hi @ge0rg I discovered that if your callsign has more than 7 letters, this error will be displayed.
I hope you'll understand my english.

**Comment by ge0rg** [comment]
@dano1o yes, this is a limitation of the APRS wire protocol. Good catch, I'll add according limitations into the app.

**Comment by ge0rg** [comment]
I've added a limit to the preference and truncate the callsign if it was set in an older version with 
5d2230ac1481ee2fc17bb90c658985ea8d021828.

Please test the [nightly APK](https://aprsdroid.org/download/builds/APRSdroid-gl-2018-10-22.apk).
