### ISSUE TITLE
Send Position button fail mode

### ISSUE THREAD

**Issue by kf7rcs** [ge0rg/aprsdroid#181]
It appears that the "Send Position" button is unresponsive at times.  I use this button to test my setup and it does not respond to me as i would expect. If "Send Position" is failing as a result of no gps solution, no error message is given.  If this error is caused by something else like a bug please evaluate and consider a fix =)  If im just setup wrong, ill figure it out eventually.  (using version 1.4)

and as always, a big warm thank you for all the hard work on this project, aprsdroid is a fantastic tool

**Comment by ge0rg** [comment]
Thanks for the report, the button launches the service with a marker to stop once a packet has been transmitted.

If you have no or bad GPS, it will wait eternally until GPS is available, I suppose this is "by design" ;-)

In the historic "medium quality" Network/GPS position, it would wait 30s after acquiring GPS to have better data as well, so all of this is a bit tricky.

I'm not sure what the expected behavior should be for the button in absence of GPS.

**Comment by kf7rcs** [comment]
Thanks!  great to know the medium quality behavior.  I think I found a verbose mode that gives me some idea whats happening.

Thanks,
