### ISSUE TITLE
Auto capitalize first letter on messages

### ISSUE THREAD

**Issue by Reid-n0rc** [ge0rg/aprsdroid#251]
I've notice that messages do not auto-capitalize the first letter, where other applications on my phone will.  I checked my settings and auto-capitalize is turned on.  

Is it possible that something in the application is preventing this?  If so, could it be chanced to allow the auto-capitalize feature on keyboards to work with messages?

**Comment by galenasphaug** [comment]
I can verify this issue, using Gboard.
I believe the message text box in APRSDroid is configured so that it won't auto capitalize.

**Comment by ge0rg** [comment]
APRSdroid has two distinct message input boxes, one in the "Messages" view when you press "Send message to..." and another one in the direct chat view for a given callsign. I've realized that the first one is missing `android:inputType="textShortMessage"` and will add it to the next build. However, the builds are currently rather broken, map-wise, due to the work on Android 10 support.

**Comment by ge0rg** [comment]
This has been fixed in https://github.com/ge0rg/aprsdroid/commit/5688c174a1ec090c8f77e35b871c867040913fd3.

I have a fix that also reworks much of the map handling in https://aprsdroid.org/download/builds/aprsdroid-gl-2020-08-18.apk

**Comment by Reid-n0rc** [comment]
Auto caps on a new message doesn't appear to be working on the new build.

**Comment by ge0rg** [comment]
I've tuned the text properties some more in efde70c9e32581b24df6b843c079dcae8b550446.

Please test this APK: https://aprsdroid.org/download/builds/aprsdroid-gl-2020-10-01.apk

**Comment by Reid-n0rc** [comment]
It works! Thank you
