### ISSUE TITLE
Are we due for a new OSM build?

### ISSUE THREAD

**Issue by MoTLD** [ge0rg/aprsdroid#292]
The latest OSM release seems to be almost 2 years old now, has enough changed in that time to be worth a new OSM build? It's the only version I use (I have a tablet, not a phone, so no always-on internet) and I haven't had any problems with it so I don't _need_ a new build, just wondering what I might be missing...

Thanks!

**Comment by MoTLD** [comment]
On second thought, actually I have had a minor issue you should know about: maps don't work if saved to external storage unless I use a third party file chooser. When I use the file chooser that comes up by default when I select "Map file name" in APRSdroid preferences, there is no way to view the whole file system; my only options (besides Recent, Images, Audio, and Downloads) are "External storage" or "Internal storage" and when I go to external storage and then choose the file, APRSdroid shows the location as "/storage/&lt;volume ID of SD card&gt;/USA.map". Then, when I try to view the map, APRSdroid gives me "Error loading map file /storage/xxxx-xxxx/USA.map!"

If I select another file manager from within that file chooser, I can instead point APRSdroid to /storage/extSdCard/USA.map and it works just fine. Also this way it should continue working even if I swap SD cards, so long as they both have the map file in the same place.

So is the file chooser a part of APRSdroid or a library it uses, or is it a part of my Android rom? If it's an Android thing then I guess there's no fixing it, but might you have APRSdroid look out for that specific situation and offer some options or advice in addition to the error message?

**Comment by nayrnet** [comment]
OSM I think is deprecated, the latest version out of the play store lets you load up map files and select OpenStreetMap.org as map source on the display page (click the eye), you can switch on the fly from google to offline maps now as needed.

probably need doc/website updates tho, I only figured it out from scrubbing the changelogs.

**Comment by penguin359** [comment]
OSM should be fully integrated with the regular APRSdroid releases now. As @nayrnet said, it's a select-able via the Eye icon on the map view. As for the file chooser, that's the file manager that comes with your flavor of Android. On the File chooser that comes with the Google Pixel 5, I can click on the home icon in the action bar (left icon at the top) and it has links to open up the Amaze, FX, and Dropbox file choosers from there.

**Comment by gunnardave** [comment]
I use the same OSM version as @MoTLD and the reason isn't specifically for OpenStreetMaps but that it supports local Mapsforge-based files.  So I find it works better than trying to cache ahead on WiFi since I'm often away from cell coverage. 

It's also only a 16 GB device so to save space I share the Mapsforge files with several apps (APRSdroid, Backcountry Navigator, Orux Maps, Locus) so that they don't all eat up storage with their own maps.

In any case the old version works fine for my use.  Since I'm on Android 4.4 (I have a really old phone) I doubt the Play store would even work on it anymore.  Mapsforge is a dead end at this point so APRSdroid OSM isn't unique in this regard.

**Comment by nayrnet** [comment]
the version from the play store loaded up my local mapforge USA.map file I torrented from my OSM days just fine.

**Comment by gunnardave** [comment]
Mapsforge isn't officially part of OSM. but I don't know what other data source they use to generate vector maps anyway.  But whatever, was not aware support for .map files was rolled into the main app so this thread is answered.  Wonder if the library was updated to use v4/v5 rather than the v3 of the library the old app used.

**Comment by nayrnet** [comment]
yeah I believe he updated the libraries because on my Pixel phone OSM flat out broke a year or so ago when I think Android10 came out.. would crash on launch because the old libraries wont run at all on the latest Android, this forced me to abandon the OSM build.

I went back to using the playstore version which worked fine, and since then he silently folded OSM back into the main branch, I didn't realize it til I got a new phone and went to setup aprsdroid again.

Docs definitely need updating to reflect the current status of offline maps, its still very much implying you need the old OSM builds so its confusing at best, and I'm sure there's others like you running antique versions blissfully unaware that offline maps are now in mainline release.

**Comment by MoTLD** [comment]
Thanks for the info, folks, I'm now running the current build with no problems. It would definitely be good if the docs were updated, but as my original question has been answered, I'm going to close it. Thanks again, 73 and be safe!

**Comment by gunnardave** [comment]
I also updated to latest version (APRSdroid-1.6.0) and it's working fine with the same v3 Mapsforge OSM maps I've been using.

It is no longer necessary to run the last OSM tagged version (APRSdroid-gl-2018-11-18_osm) for offline maps.

**Comment by kk7ds** [comment]
Running the latest play build on a fully updated pixel 3, I get no offline map display and mostly just APRSdroid crashes when I display the map in OSM mode. I'm using us-pacific.map from the mapsforge v3 directory. Can someone report what exact map file they're using so I can try it? I don't need the full-sized US file, but will do that if for some reason that one works and the per-region ones do not.

**Comment by gunnardave** [comment]
My maps came from here:
https://www.openandromaps.org/en/downloads/usa_en

This is the direct download of the map I’m using with no apparent issue:
https://ftp.gwdg.de/pub/misc/openstreetmap/openandromaps/maps/usa/Utah_Colorado_V3.zip

**Comment by kk7ds** [comment]
Thanks, I should have circled back - I eventually got it working. Neither the us-pacific or us-west maps work for me from mapsforge v3. But, the per-state ones do. Looks like I should get those from openandromaps as they're newer.

Thanks!
