### ISSUE TITLE
Notification ringtone selection does not stick

### ISSUE THREAD

**Issue by turbo2ltr** [ge0rg/aprsdroid#94]
1.2.3 (OSM) 2014-09-14
I tried several tablets ranging from Android 2.2 to 4.4.4 and none will remember the ringtone selected for any of the notifications.  It always defaults to none. I believe this was an issue in previous versions as well.  Vibrate works and is triggered properly, but never get a ringtone to play despite selecting it several times..

**Comment by ge0rg** [comment]
Thanks for the report. I've seen that problem as well, but thought it has to do with my phone's firmware. I will investigate and update this ticket.

**Comment by OctopusKat** [comment]
Seconded. OnePlus One - running Android 5.0.2 (Cyanogenmod 12.0) has the same problem with APRSdroid v1.3.0-68-g4c623fa (2015-03-20, OSM build).

**Comment by ge0rg** [comment]
Sometimes it is only a little piece of information that the author overlooks. The problem is only affecting the OSM build, and once I realized that (which I didn't before), I was able to fix it in 7c4cd90ebbe3b415ff1975edf6997203abf020cc.

[Fixed APK](https://aprsdroid.org/download/builds/APRSdroid-gl-2015-06-02_osm.apk)
